---
#Variables
variables:
  INSTANCE_REPO_PIPELINE_IMAGE: DOCKER_IMAGE_NAME
  INSTANCE_REPO_PIPELINE_IMAGE_TAG: DOCKER_IMAGE_TAG

#Rules
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

#Stages
stages:
  - extend-pipeline

extend-the-gh-pipeline:
  stage: extend-pipeline
  image:
    name: ${INSTANCE_REPO_PIPELINE_IMAGE}:${INSTANCE_REPO_PIPELINE_IMAGE_TAG}
  script:
    - python3 scripts/apply_envgene_patch.py PATH_TO_COMPONENT
    - python3 scripts/git_commit.py
  artifacts:
    paths:
      - extended_github_instance_pipeline/
