name: 'Run Tests'
description: 'Run Qubership Envgene tests'

inputs:
  python-version:
    description: 'Python version to use for tests'
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            curl \
            && rm -rf /var/lib/apt/lists/*
        
        if [ -f dependencies/pip.conf ]; then
            mkdir -p /etc/pip
            cp dependencies/pip.conf /etc/pip.conf
        fi
        
        if [ -f dependencies/sources.list ]; then
            cp dependencies/sources.list /etc/apt/sources.list
        fi
        
        pip install --no-cache-dir -r dependencies/tests_requirements.txt
        
        if [ -f python/build_modules.sh ]; then
            chmod +x python/build_modules.sh
            ./python/build_modules.sh
        fi

        curl -LO https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
        mv sops-v3.9.0.linux.amd64 /usr/local/bin/sops
        chmod +x /usr/local/bin/sops
    
    - name: ENVGENE HELPER test
      shell: bash
      run: |
        cd python/envgene/envgenehelper
        pytest --capture=no -W ignore::DeprecationWarning --junitxml=../../../junit.xml
        cd ../../..
        mv junit.xml junit_envgenehelper.xml  
    
    #- name: BUILD ENV test
    #  shell: bash
    #  run: |
    #    cd scripts/build_env
    #    pytest --capture=no -W ignore::DeprecationWarning --junitxml=../../junit.xml
    #    cd ../..
    #    mv junit.xml junit_build_env.xml
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: CLI Java Module tests
      shell: bash
      run: |
        cd build_effective_set_generator_java

        if [ -f pom.xml ]; then
          echo "Running Maven tests..."

          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw test
          else
            mvn test
          fi

          find effective-set-generator/target/surefire-reports -name "*.xml" -exec cat {} \; > ../junit_java.xml
        else
          echo "pom.xml not found, skipping tests."
        fi


    - name: Merge test results
      shell: bash
      run: |
        junitparser merge junit_build_env.xml junit_envgenehelper.xml junit_java.xml junit.xml    

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: junit.xml

    - name: Upload test environments
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test_artifact
        path: tmp/ 