service-activator-integration-cred:
  type: usernamePassword
  data:
    username: "user-placeholder-123"
    password: "pass-placeholder-123"
tibco-integration-cred:
  type: usernamePassword
  data:
    username: "user-placeholder-123"
    password: "pass-placeholder-123"
